"use client";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "./snippets/sidebar/sidebar";

import util from "./utils/util";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Dorakart",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col overflow-hidden`}
      >
        <div className="">
          <div className="ml-10 w-[16vw] h-[90vh] bg-[#F7F7F7] text-white overflow-hidden rounded-xl my-10">
            <div className="text-center font-bold text-xl text-black pt-4">🛒 Dorakart </div>
            <SideBar />
          </div>

          <div className="w-[78vw] pl-1  absolute top-0 left-[19vw] h-[96vh] rounded-xl overflow-hidden scroll ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
